// flow-typed signature: 345d6a2893721f9bbe4ae95fa04ce044
// flow-typed version: <<STUB>>/glow_v^1.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glow/cli' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/cli' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/constants' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Env' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/index' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Interface' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Lang' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Logger' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Printer' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/Runner' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/types' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/utils/flow' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/utils/fs' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/utils/locations' {
  declare module.exports: any;
}

declare module 'glow/dist/legacy/utils/timers' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/cli' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/constants' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Env' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/index' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Interface' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Lang' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Logger' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Printer' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/Runner' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/types' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/utils/flow' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/utils/fs' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/utils/locations' {
  declare module.exports: any;
}

declare module 'glow/dist/modern/utils/timers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glow/cli.js' {
  declare module.exports: $Exports<'glow/cli'>;
}
declare module 'glow/dist/legacy/cli.js' {
  declare module.exports: $Exports<'glow/dist/legacy/cli'>;
}
declare module 'glow/dist/legacy/constants.js' {
  declare module.exports: $Exports<'glow/dist/legacy/constants'>;
}
declare module 'glow/dist/legacy/Env.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Env'>;
}
declare module 'glow/dist/legacy/index.js' {
  declare module.exports: $Exports<'glow/dist/legacy/index'>;
}
declare module 'glow/dist/legacy/Interface.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Interface'>;
}
declare module 'glow/dist/legacy/Lang.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Lang'>;
}
declare module 'glow/dist/legacy/Logger.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Logger'>;
}
declare module 'glow/dist/legacy/Printer.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Printer'>;
}
declare module 'glow/dist/legacy/Runner.js' {
  declare module.exports: $Exports<'glow/dist/legacy/Runner'>;
}
declare module 'glow/dist/legacy/types.js' {
  declare module.exports: $Exports<'glow/dist/legacy/types'>;
}
declare module 'glow/dist/legacy/utils/flow.js' {
  declare module.exports: $Exports<'glow/dist/legacy/utils/flow'>;
}
declare module 'glow/dist/legacy/utils/fs.js' {
  declare module.exports: $Exports<'glow/dist/legacy/utils/fs'>;
}
declare module 'glow/dist/legacy/utils/locations.js' {
  declare module.exports: $Exports<'glow/dist/legacy/utils/locations'>;
}
declare module 'glow/dist/legacy/utils/timers.js' {
  declare module.exports: $Exports<'glow/dist/legacy/utils/timers'>;
}
declare module 'glow/dist/modern/cli.js' {
  declare module.exports: $Exports<'glow/dist/modern/cli'>;
}
declare module 'glow/dist/modern/constants.js' {
  declare module.exports: $Exports<'glow/dist/modern/constants'>;
}
declare module 'glow/dist/modern/Env.js' {
  declare module.exports: $Exports<'glow/dist/modern/Env'>;
}
declare module 'glow/dist/modern/index.js' {
  declare module.exports: $Exports<'glow/dist/modern/index'>;
}
declare module 'glow/dist/modern/Interface.js' {
  declare module.exports: $Exports<'glow/dist/modern/Interface'>;
}
declare module 'glow/dist/modern/Lang.js' {
  declare module.exports: $Exports<'glow/dist/modern/Lang'>;
}
declare module 'glow/dist/modern/Logger.js' {
  declare module.exports: $Exports<'glow/dist/modern/Logger'>;
}
declare module 'glow/dist/modern/Printer.js' {
  declare module.exports: $Exports<'glow/dist/modern/Printer'>;
}
declare module 'glow/dist/modern/Runner.js' {
  declare module.exports: $Exports<'glow/dist/modern/Runner'>;
}
declare module 'glow/dist/modern/types.js' {
  declare module.exports: $Exports<'glow/dist/modern/types'>;
}
declare module 'glow/dist/modern/utils/flow.js' {
  declare module.exports: $Exports<'glow/dist/modern/utils/flow'>;
}
declare module 'glow/dist/modern/utils/fs.js' {
  declare module.exports: $Exports<'glow/dist/modern/utils/fs'>;
}
declare module 'glow/dist/modern/utils/locations.js' {
  declare module.exports: $Exports<'glow/dist/modern/utils/locations'>;
}
declare module 'glow/dist/modern/utils/timers.js' {
  declare module.exports: $Exports<'glow/dist/modern/utils/timers'>;
}
declare module 'glow/index' {
  declare module.exports: $Exports<'glow'>;
}
declare module 'glow/index.js' {
  declare module.exports: $Exports<'glow'>;
}
